### PR TITLE
Feat/better strings

### PR DESCRIPTION
**Pull request by omangin**
Adds strings and string expression representations as detailed in issue #98.

### CODE REVIEW

**Comment by omangin** [comment]
One test is failing because of the outdated pypy3 version. Should be fixed after merging #164.

**Comment by sciunto** [comment]
You can rebase, #164 has been merged.

**Comment by sciunto** [comment]
I'll try to have a look soon...

**Comment by sciunto** [comment]
@Phyks Do you have time to have a look. I'm running out of time and energy these days... :(

**Comment by Phyks** [comment]
Sure, I'll try to have a look by the end of the week.

**Comment by Phyks** [comment]
@sciunto I gave a look at the PR, and it looks good. At least, I did not see anything making me scream. However, I should emphasize that I am highly unfamiliar with Bibtex strings (have never used them previously) and may have missed something :/

**Comment by sciunto** [comment]
If it looks good to both of you, feel free to merge. I'm not going to have brain time for that, for the next couple of months. ;)

**Comment by omangin** [comment]
Thank you for the comments. I've just rebased the branch on the master.
I believe it is safe to merge, specially since the string representation is not exposed by default (the default behavior converts the bibtex strings to the value they represent). I'll however write some documentation on the feature before doing the merge and mark it as experimental for now.

**Pull request merged**
