### PR TITLE
Fix Travis build with pypy3

### PR DESCRIPTION
**Pull request by Phyks**
Closes issue #166.

### CODE REVIEW

**Comment by Phyks** [comment]
Ok, so it is not working, see [this build](https://travis-ci.org/sciunto-org/python-bibtexparser/jobs/251706138). I'll try to get more infos from Travis :/

**Comment by Phyks** [comment]
So, there is an issue with `pypy2.7` at Travis, they have an internal ticket for this :/

Then, usable versions at the moment are:

```
pypy-2.6.1                 14.04
pypy-5.0.0           12.04 14.04
pypy-5.0.1           12.04 14.04
pypy-5.1.1           12.04 14.04
pypy-5.1             12.04 14.04
pypy-5.3.1           12.04 14.04
pypy-5.3             12.04 14.04
pypy-5.4.1           12.04 14.04
pypy-5.4             12.04 14.04
pypy-5.6.0           12.04 14.04
pypy-5.6             12.04 14.04
pypy-5.7.1                 14.04
pypy-5.7                   14.04
pypy3-2.4.0          12.04 14.04
pypy3-2.4            12.04 14.04
pypy3.3-5.2-alpha1   12.04 14.04
pypy3.3-5.5-alpha    12.04 14.04
pypy3.5                    14.04
pypy3.5-5.7.1-beta         14.04
pypy3.5-5.8.0        12.04 14.04
```

**Comment by sciunto** [comment]
could you deactivate pypy2 and open a ticket. Then, we can merge this one.

**Comment by Phyks** [comment]
I'm in touch with Travis support to try to debug their Pypy setup (which is kind of heavily broken apparently). I'll try to see if I can get anything working by the weekend, which would fix both Pypy and Pypy3. Otherwise, I'll disable Pypy2 and open a separate PR I think.

**Comment by Phyks** [comment]
@sciunto here we go, tests are passing again on Travis for Pypy (and Pypy3). This is not tested against latest Pypy version though, due to Travis limitations.

I think we can merge this one and close #166. We should update from time to time the pypy versions we are testing against, whenever a new version is available at Travis, but this info is not really publicly accessible :/ Any ways, there does not seem to be much changes on Travis tickets and I am not sure they will fix this anytime soon :/

**Comment by sciunto** [comment]
Great.

Yep, I know that travis is not so transparent. That's why I dislike using proprietary services... :(

**Pull request merged**
