### PR TITLE
accept extra characters

### PR DESCRIPTION
**Pull request by noahdesu**
This patch accept string macros with hyphen and colon:

@string{pub-ieee-std = {IEEE}}
@string{pub-ieee-std:adr = {New York, NY, USA}}

and accept entry field names with period:

Dc.Date = {2004-01},

### CODE REVIEW

**Comment by sciunto** [comment]
Thank you very much @noahdesu ! Would you like to modify an existing test to reflect these changes?

**Comment by Phyks** [comment]
@noahdesu any news on this? Thanks!

**Comment by noahdesu** [comment]
@sciunto @Phyks this fix is still relevant in master, and i updated this PR to include tests for the cases. Sorry about the two year delay :)

**Comment by sciunto** [comment]
Great! Many thanks

**Pull request merged**
