### PR TITLE
[WIP] bwriter: protection uppercase

### PR DESCRIPTION
**Pull request by sciunto**
- [ ] doc
- [x] list of fields
- [ ] enhance test
- [ ] one test skipped

### CODE REVIEW

**Comment by Phyks** [comment]
@sciunto Can I ask you to give me some background on this PR? I can try to have a look and finish it if you think this is important before tagging 0.7.0. Thanks!

**Comment by sciunto** [comment]
The point is that fields like titles may have upper case letters, intended to be printed like that. But, for that, it needs to be protected with braces {}. Often, editors do not do a proper work on that.

This should not block the next release though. It's an enhancement. Targeting to 0.8.0 is ok for me.

**Comment by michaelfruth** [comment]
I'ld like to take care of this feature 🥳 (as I'm also interested in this feature for my own [Python-BibTex-Handler](https://github.com/michaelfruth/latex-bibliography-helper)).

**Comment by MiWeiss** [comment]
Hi @michaelfruth 

Thanks again (and again :-) ) for your great effort. My answer here equally goes for #244.

In the background, I've been working on preparing python-bibtexparser `v2.0`, which is a complete re-write of the library, fixing several of its structural issues (error handling, performance and encoding issues to name a few). While I'll be able to take over your previous PRs pretty much unchanged into the new codebase, for what regards @244 and #126 that's probably not the case and I'd hate to have you waste your time on something becoming obsolete soon anyways.

Thus, I wondered if you were interested into joining the dev of v2.0. At the moment, as I'm still laying out the overall architecture, there's no public branch yet, but if you're interested, I'd happily drop you an email with some more info.

**Comment by michaelfruth** [comment]
Hi @MiWeiss,

No problem for delayed answers, I was also very busy for the last few days ;-). I just try to contribute once I've some time.

Yes, I'ld like to join the development ov Version 2.0! 🥳  Just drop me a message.

**Pull request closed without merging**
