### PR TITLE
Bugfix name split

### PR DESCRIPTION
**Pull request by tdegeus**
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/441

### CODE REVIEW

**Comment by MiWeiss** [comment]
Hey. Thanks for all your PRs! Very much appreciated!

> @MiWeiss Would you have time to review my PRs? 

Sorry for the wait (although reviews within a single-digit number of days appear to be still pretty compared to what I've seen all around github :-P)

That said, have you considered becoming a co-maintainer of bibtexparser? Given your long history with it, and your PRs, that would certainty help the project!

**Comment by tdegeus** [comment]
Hi! No worries. It was just that I had a little bandwidth so pushing some things through is convient 

Yes, I would not mind co-maintaining

**Review by MiWeiss — APPROVED** [review]
I'm merging this, as it is ready. Feel free continue the discussion about co-maintainership here (tagging me to make sure I get notified) or find other ways to contact me on [mweiss.ch](https://mweiss.ch)

**Comment by tdegeus** [comment]
I did not realise you are around the corner (sort of) 😃

**Comment by tdegeus** [comment]
Also not sure what you mean by *discussing* co-maintainership

**Comment by MiWeiss** [comment]
> Also not sure what you mean by discussing co-maintainership

You replied before I submitted my review comment :-) 

> Yes, I would not mind co-maintaining

Discussion resolved. :-P Thanks a lot, @tdegeus - that's a great step for the project.

Some comments:

- AFAIK, your PRs will still require a review. For trivial changes, I'll just give a blind yes and not argue about details ;-) 
- I'll assign you as a reviewer to my PRs if I am not certain about some stuff. While we're still in beta, I won't be overly hesitant with direct merging, but feel free to open an issue if you disagree with anything I merged.
- Feel free to review PRs of other contributors. For large, high-impact changes it's probably best if we get aligned before merging, but anything small or non-functional can be merged without my input. 
- For v2: If you want me to release a new version, just create a PR with the version bumped. I'll then merge and tag it, which will automatically trigger the release. Make sure to always include the beta-part (e.g. 2.0.0**b7**), as otherwise it will be released as stable version and auto-upgrade all dependents which did not specify a version in their requirements. We don't want that for now ;-)
- Drop me an email to code@mweiss.ch if you need anything and don't get a response here within reasonable time.

Does this all make sense? Thanks again for taking on this role!

**Comment by MiWeiss** [comment]
> I did not realise you are around the corner (sort of) 😃

It seems so. François (the owner of sciunto-org) is also quite close, if I am not mistaken. At least we won't have time-zone issues :-P

**Pull request merged**
