### PR TITLE
Add ordering by ascending/descending to btexwriter

### LINKED ISSUE #243: BibTexWriter().order_entries_by should support reverse ordering.
`order_entried_by` should support reverse order like:
```python
    writer = BibTexWriter()
    writer.order_entries_by = ('-year')
```

### PR DESCRIPTION
**Pull request by runderwood**
Fixes #243: order by multiple keys in various directions

Also: add unittest2 to tox deps

### CODE REVIEW

**Comment by runderwood** [comment]
Bump. @sciunto

**Comment by MiWeiss** [comment]
Hi @andrejberg.

I just joined the project and wanted to give you a quick heads up. 
This has been stale for a long time, as the project was looking for a new maintainer. Are you still interested in this PR, i.e., would you mind resolving the merge conflict and receiving a review?

Otherwise, just tell me and I'll see if we can re-assign the issue.

**Comment by michaelfruth** [comment]
Maybe we can re-use the `SortingStrategy` for this feature once #317 is merged?

Maybe something like:
```
# Option 1:

# Manual ordering is possible by specifying a list or automatic order by specifying a sorting strategy..
self.order_entries_by: Union[SortingStrategy, List[str]] = ...
```

or similar to `display_order`:
```
# Option 2:

self.order_entries_by = ('ID', )
# Items not specified in self.order_entries_by are ordered based on the given strategy.
self.order_entries_strategy = ...
```

I would go with option 2 as it would be similar to `display_order` and it provides more flexibility.

**Comment by MiWeiss** [comment]
See answer in #126 before continuing this :-)

**Comment by MiWeiss** [comment]
pr and issue stale and for v1, closing both. 

feel free to comment for a re-open, when there's still interest in fixing this.

**Comment by runderwood** [comment]
I can't remember who initiated this, but I thought it useful at the time. Happy to clean it up and do a merge over the next few days. Or if you think it not worth the effort, I'll let it slide into history.

**Comment by MiWeiss** [comment]
Thanks @runderwood.  There are two points to consider:

- For what regards the technical depth introduced by this PR, the change is not negligible, but still ok.
- I doubt there is a high need; we just released v2-beta, which is a complete library re-write (currently on the main branch, but not yet on pypi). It is not yet feature complete, but I assume that within the next few months, most new users of bibtexparser will start using v2. Relatively soon, I will stop the active maintenance of v1. Thus, your PR (which only applies to v1) would probably not reach too many users. 

I leave the choice of whether you want to invest any more time on this to you. If you do, I will of course review and, if possible, merge. IMHO however, its probably not worth it. If you wanna collaborate though, there are still a bunch of things to be done for v2 (a bunch of issues labeled `v2` will be opened in the next few days).

Best,
Michael

**Comment by runderwood** [comment]
Sounds good.  Guess it'd make more sense to put any effort into v2. If you have specific things you'd like help with, do let me know. And I'll take a look at v2-related items. Thanks!

**Comment by MiWeiss** [comment]
Great! Any help is appreciated.

Regarding specific things for v2; besides the issues labelled accordingly just testing it (as a user) and giving feedback would be highly appreciated ;-)

**Pull request closed without merging**
